### ISSUE TITLE
Search posts based on search keyword

### ISSUE THREAD

**Issue by franklinnwren** [cs130-w21/15#10]
#3
## User Story
As a User, I would like to search the posts I want to read by keywords and other analytics attributions.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria

- [x] Given a keyword, the user should be able to search a post that contains the keyword on the title or the content of the post
- [x] If there are no matching post given the search keyword, remind the user that there is no matched result and encourage them to try other keywords.

**Comment by paroniriaa** [comment]
Done
