### ISSUE TITLE
Blog visualization by word cloud

### ISSUE THREAD

**Issue by panzhufeng** [cs130-w21/15#2]
#4 
## User Story
As a **user**, I would like **visualize the text content of a blog** so that **I can decide if I will read it.**

## Detailed Description
For each posted blog article, the platform will generate a word cloud image to visualize the content. The font of each word in the word cloud image represents the word importance for the article. Users can quickly decide if they want to read the article from the visualization results

## Acceptance Criteria
- [x] Given **a text string that represents a blog**, then **a model generates the importance for each word.**
- [x] Given **word importance for a blog**, then **plot a word cloud image.**
- [x] Given **generated word cloud image**, then **show it on the front-end page.**

**Comment by yifan6082870** [comment]
Done

**Comment by paroniriaa** [comment]
Done
