### ISSUE TITLE
Word cloud representation for individual blogs

### ISSUE THREAD

**Issue by franklinnwren** [cs130-w21/15#4]
## Epic
Description and User Benefits:
Word cloud is an illustrative image representation of a passage or an article which could demonstrate the keywords used in that passage, and mark the significance of those words by their respective sizes. Through word cloud, it will be very convenient for users to get an idea about what the blogs are all about even before they read them. That will allow the users to pick the type of blogs about their most interested topics at a minimum time cost. Also, the blog authors could use the word cloud summaries to check whether they conveys the main points in their passages. The different colors and forms of the word clouds will also enhance the reading experiences of the users. 

User Action:
- Users should be able to view the word cloud representation of each blog on the webpage.

## User Stories
- [ ] Blog visualization by word cloud #2 
- [x] Keyword extraction #8

**Comment by yifan6082870** [comment]
Done
