### ISSUE TITLE
Analytics report viewing

### ISSUE THREAD

**Issue by elffiona** [cs130-w21/15#5]
#3 
## User Story
As a **User**, I would like **see the analytical report generated on the audience's behavioral data** so that **I can use some of its information for needed research and better prepare myself for further contributions in the same field**.

## Detailed Description
For each blog posted to the main page, the platform keeps track of user behaviors related to that specific post. These data collected could potentially include the number of mouse clicks to the post, the total reading time, and the average reading time on each paragraph.

## Acceptance Criteria
- [ ] Given **a post**, then **the audience behavior should be tracked and recorded**
- [ ] Given **a user click on the "view analytics" button**, then **the audience behavioral data should be displayed using graphs like histogram and texts**

**Comment by yifan6082870** [comment]
Done
