### ISSUE TITLE
Keyword Extraction

### ISSUE THREAD

**Issue by panzhufeng** [cs130-w21/15#8]
## User Story
As a **user**, I would like **extracting keywords for each article automatically** so that **other users can retrieve my articles by tags accordingly**.

## Detailed Description
For a given article, represented as a string, there will be a keyword extraction model that can extract the most informative keywords.

## Acceptance Criteria
- [x] Given **an input string**, then **the model returns a list of keywords**,

**Comment by vufg** [comment]
Finished the naive TF-IDF model. #9

**Comment by panzhufeng** [comment]
Finished the naive TF-IDF model. #9
